/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentRouterSol from "./AgentRouter.sol";
export type { agentRouterSol };
import type * as mocks from "./mocks";
export type { mocks };
